print('Faça um programa que leia a largura e a altura de uma parede em metros, calcule sua área e quantidade\nde tinta necessaria para pinta-la.')
print('Sabendo que cada litro de tinta pinta uma área de 2m²')
print('')
largura = float(input('Digite a altura da parede em metros: '))
altura = float(input('Digite a altura da parede em metros: '))
area = (largura*altura)
litros = (area/2)
print('A área da parede é de: {:.2f}m²'.format(area))
print('A quantidade de tinta necessaria para pintar está parede é de: {:.2f} litros'.format(litros))
